# Supervised Model
## training phase
> inputs <br>⬇
>
> layer 1 <br>⬇
>
> layer 2 <br>⬇
>
> layer 3 <br>⬇
>  <p> &emsp; &emsp; &emsp; &emsp; training</p> <br>
> output ➡ loss function ⬆
## tensor board ...
## testing phase

## competetional graph

In [7]:
import os
import tensorflow as tf

In [12]:
import os
import tensorflow as tf

# Turn off TensorFlow warning messages in program output
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# Define computational graph
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

addition = tf.add(X, Y, name="addition")


# Create the session
with tf.Session() as session:

    result = session.run(addition, feed_dict={X: [[1], [2], [3]], Y: [4, 5, 6]})
    print(result)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


## option for loading data